version: '3.8'

services:
  app:
    build: .
    container_name: java-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: ${LOCAL_MONGODB_CONNECTION_STRING}
      QUARKUS_MONGODB_DATABASE: ${LOCAL_MONGODB_DATABASE}
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: